### ISSUE TITLE
int type does not use number field

### ISSUE THREAD

**Issue by jfoshee** [srkirkland/Html5MvcTemplates#1]
I have an int property in my model but the number template was not automatically selected.  
I worked around this by adding [UIHint("number")] to the property.

Thanks!

**Comment by srkirkland** [comment]
Yup, you have to give your property the [UIHint("number")] attribute as you mentioned.  The main reason I did this was because I didn't want to have to create editors for each number type (int, double, float, decimal, etc), and also because I mostly tried to stay away from directly overwriting the editors for primitive types (with the exception of DateTime).
